version: 2
jobs:
  build:
    working_directory: ~/TestAutomation
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
#       - run: sudo chown -R $(whoami)
      - run: sudo npm cache clean --force
      - run: sudo rm -rf node_modules
      - run: npm install
      - run: sudo npm i -g mocha
      - run: sudo mocha tests/*
#       - run:
#           name: npm-restore-deps
#           command: npm install
#           working_directory: TestAutomation
#       - run:
#           name: app-auto-testing
#           command: npm test
      
#           working_directory: TestAutomation
